### ISSUE TITLE
麻烦问一下，是不是选取的节点不同，请求方式也不一样啊

### ISSUE THREAD

**Issue by loneboygan** [lorenzourera/solana-auto-sell-bot#2]
![image](https://github.com/lorenzourera/solana-auto-sell-bot/assets/72730341/7679423d-436f-4713-9af8-6f353d7948d8)

**Comment by loneboygan** [comment]
我知道了，你是用的这个节点helius

**Comment by iharrye** [comment]
Hi, is there a fix for this? I have tried using different nodes. thanks
